// Generated by CoffeeScript 1.9.2
var client, doshit;

doshit = require('../');

client = doshit('redis://docker:6379', 'dothis');

client.task('add', {
  a: 1,
  b: 5
}, function(err, result, task) {
  if (err != null) {
    return console.error(err);
  }
  return console.log("1 + 5 = " + result);
});

client.task('echo', {
  text: 'YARR'
}, function(err, result, task) {
  if (err != null) {
    return console.error(err);
  }
  return console.log("YARR in, " + result + " out");
});

client.task('error', {}, function(err, result, task) {
  if (err != null) {
    return console.error(err);
  }
});
