FROM python:3.7-slim
COPY python-doshit /install/doshit
RUN pip install -r /install/doshit/requirements.txt
RUN cd /install/doshit && python setup.py install
COPY python-doshit/examples /doshit-examples
WORKDIR /doshit-examples
