// Generated by CoffeeScript 1.9.2
var client, doshit;

doshit = require('../');

client = doshit('redis://docker:6379', 'doshit');

client.on('success', function(result, task) {
  return console.log(task);
});

client.task('add', {
  a: 1,
  b: 5
}, function(err, result, task) {
  if (err != null) {
    client.quit();
    console.error(err);
    return;
  }
  console.log("1 + 5 = " + result);
  return client.task('echo', {
    text: 'YARR'
  }, function(err, result, task) {
    if (err != null) {
      client.quit();
      console.error(err);
      return;
    }
    console.log("YARR in, " + result + " out");
    return client.task('error', {}, function(err, result, task) {
      if (err != null) {
        client.quit();
        console.error(err);
        return;
      }
      return client.quit();
    });
  });
});
